default: &default
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  adapter: sqlite3
  username: root
  password:
  host: localhost
  database: db/development.db

test:
  <<: *default
  adapter: sqlite3
  username: root
  password:
  host: localhost
  database: db/development.db

production:
  <<: *default
  adapter: postgresql
  url: <%= ENV['DATABASE_URL'] %>
